### PR TITLE
refactor: major code quality improvements and general overhaul

### PR DESCRIPTION
**Pull request by Kek5chen**
Check commit comments for more information and learning material.

I put work into these so you can learn a bit:
https://github.com/Kek5chen/RedAntiKillerPotions/commit/3712e112ce6c9567ad945e1194b09c66b97793d7

Please test before merging.

### CODE REVIEW

**Comment by RedstoneFuture** [comment]
Thanks for the feedback. Some points I will apply to all plugins as refactoring, because I find them very useful. Others I do not prefer yet, but will remember the spelling.

**Comment by Kek5chen** [comment]
Since i know that this plugin is being actively used on the server it might make sense to still use the changes for the better instead of closing it

**Comment by RedstoneFuture** [comment]
@Kek5chen -> https://github.com/RedstoneWorld/RedAntiKillerPotions/commit/8e05ce05000424e645df047b4a5e80a62580fa28

**Comment by Kek5chen** [comment]
Ah, so we're just copying other peoples code now. Cool.

**Pull request closed without merging**
